---
  root: true

  env:
    browser: true
    node:    true
    es6:     true

  parser: babel-eslint

  parserOptions:
    ecmaVersion: 7
    sourceType: module

  extends:
    - 'eslint:recommended'

  rules:
    accessor-pairs:
      - 2
    array-bracket-spacing:
      - 2
      - always
    array-callback-return:
      - 1
    arrow-body-style:
      - 1
    arrow-parens:
      - 2
      - always
    arrow-spacing:
      - 2
    block-scoped-var:
      - 1
    block-spacing:
      - 2
    brace-style:
      - 2
    callback-return:
      - 1
    camelcase:
      - 2
      - properties: never
    comma-dangle:
      - 1
      - always-multiline
    comma-spacing:
      - 2
    comma-style:
      - 2
    complexity:
      - 2
    constructor-super:
      - 2
    computed-property-spacing:
      - 2
      - always
    consistent-return:
      - 1
    curly:
      - 2
    default-case:
      - 1
    dot-location:
      - 2
      - property
    dot-notation:
      - 1
    eol-last:
      - 2
    eqeqeq:
      - 2
      - allow-null
    generator-star-spacing:
      - 2
      - both
    guard-for-in:
      - 2
    id-length:
      - 2
      - min: 2
        max: 25
        exceptions:
          - i
          - j
          - $
          - _
    key-spacing:
      - 2
      - align: value
    keyword-spacing:
      - 2
    linebreak-style:
      - 2
      - unix
    lines-around-comment:
      - 2
      - beforeLineComment: true
        beforeBlockComment: true
    max-depth:
      - 2
    max-len:
      - 2
      - code: 100
        tabWidth: 4
        ignoreUrls: true
    max-nested-callbacks:
      - 2
      - 5
    max-params:
      - 1
      - 5
    max-statements:
      - 1
      - 50
    max-statements-per-line:
      - 2
    new-cap:
      - 2
    new-parens:
      - 2
    newline-after-var:
      - 2
    newline-before-return:
      - 2
    newline-per-chained-call:
      - 2
    no-array-constructor:
      - 2
    no-bitwise:
      - 1
      - int32Hint: true
    no-caller:
      - 2
    no-catch-shadow:
      - 2
    no-class-assign:
      - 2
    no-confusing-arrow:
      - 2
      - allowParens: true
    no-console:
      - 0
    no-const-assign:
      - 2
    no-continue:
      - 1
    no-delete-var:
      - 2
    no-div-regex:
      - 1
    no-dupe-class-members:
      - 2
    no-duplicate-imports:
      - 2
    no-else-return:
      - 1
    no-empty-function:
      - 2
    no-eval:
      - 2
    no-extra-bind:
      - 1
    no-extra-label:
      - 1
    no-floating-decimal:
      - 1
    no-implicit-globals:
      - 2
    no-implied-eval:
      - 2
    no-invalid-this:
      - 1
    no-iterator:
      - 2
    no-label-var:
      - 2
    no-lone-blocks:
      - 1
    no-lonely-if:
      - 1
    no-loop-func:
      - 2
    no-magic-numbers:
      - 2
    no-mixed-requires:
      - 1
    no-mixed-spaces-and-tabs:
      - 2
      - smart-tabs
    no-multiple-empty-lines:
      - 1
      - max: 2
        maxBOF: 1
        maxEOF: 1
    no-native-reassign:
      - 2
    no-negated-condition:
      - 1
    no-nested-ternary:
      - 1
    no-new-func:
      - 2
    no-new-object:
      - 2
    no-new-require:
      - 2
    no-new-symbol:
      - 2
    no-new-wrappers:
      - 2
    no-octal:
      - 2
    no-octal-escape:
      - 2
    no-path-concat:
      - 2
    no-plusplus:
      - 2
      - allowForLoopAfterthoughts: true
    no-proto:
      - 2
    no-redeclare:
      - 2
    no-return-assign:
      - 2
    no-script-url:
      - 2
    no-self-assign:
      - 2
    no-self-compare:
      - 2
    no-sequences:
      - 2
    no-shadow:
      - 2
      - builtinGlobals: true
        allow:
          - cb
          - done
          - resolve
          - reject
    no-shadow-restricted-names:
      - 2
    no-spaced-func:
      - 2
    no-this-before-super:
      - 2
    no-throw-literal:
      - 2
    no-trailing-spaces:
      - 2
    no-undef:
      - 2
    no-undef-init:
      - 2
    no-undefined:
      - 2
    no-unmodified-loop-condition:
      - 2
    no-unneeded-ternary:
      - 2
    no-unused-expressions:
      - 2
      - allowShortCircuit: true
        allowTernary: true
    no-unused-vars:
      - 2
    no-use-before-define:
      - 2
    no-useless-call:
      - 2
    no-useless-concat:
      - 1
    no-useless-constructor:
      - 2
    no-useless-escape:
      - 1
    no-var:
      - 2
    no-void:
      - 1
    no-whitespace-before-property:
      - 2
    no-with:
      - 2
    object-curly-spacing:
      - 2
      - always
    object-shorthand:
      - 1
    operator-assignment:
      - 2
      - always
    operator-linebreak:
      - 2
      - before
    prefer-arrow-callback:
      - 1
    prefer-const:
      - 1
    prefer-reflect:
      - 1
    prefer-rest-params:
      - 1
    prefer-spread:
      - 1
    prefer-template:
      - 1
    quote-props:
      - 2
      - as-needed
    quotes:
      - 2
      - single
      - avoidEscape: true
    radix:
      - 1
    require-jsdoc:
      - 2
      - require:
          FunctionDeclaration: true
          MethodDefinition: true
          ClassDeclaration: true
    require-yield:
      - 2
    semi:
      - 2
    semi-spacing:
      - 2
    space-before-blocks:
      - 2
    space-before-function-paren:
      - 2
      - never
    space-in-parens:
      - 2
      - always
    space-infix-ops:
      - 2
    space-unary-ops:
      - 2
      - overrides:
          '!': true
          '!!': true
    spaced-comment:
      - 2
    strict:
      - 2
    template-curly-spacing:
      - 2
      - always
    valid-jsdoc:
      - 2
      - requireReturn: false
        requireReturnDescription: false
        prefer:
          returns: return
    wrap-iife:
      - 2
      - inside
    wrap-regex:
      - 2
    yield-star-spacing:
      - 2
      - both
    yoda:
      - 2
      - always
