---
  root: true

  env:
    browser: true

  parser: babel-eslint

  extends:
    - wesm87

  rules:
    semi:
      - error
      - never
    class-methods-use-this:
      - off
    no-console:
      - off
    no-underscore-dangle:
      - off
    no-restricted-syntax:
      - error
      - ForInStatement
      - LabeledStatement
      - WithStatement
    wrap-iife:
      - error
      - outside
    prefer-arrow-callback:
      - off
    import/prefer-default-export:
      - off
