---
  root: true

  env:
    browser: true

  parser: babel-eslint

  extends:
    - wesm87

  rules:
    class-methods-use-this:
      - off
    no-console:
      - off
    no-underscore-dangle:
      - off
    no-restricted-syntax:
      - error
      - ForInStatement
      - LabeledStatement
      - WithStatement
