sudo: false

language: node_js

node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

cache:
  - node_modules

install:
  - npm install

script:
  - npm run travis

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/03714729ba7967ebf124
    on_success: change
    on_failure: always
    on_start: never

addons:
  code_climate:
    repo_token: 880fba2220123f5927f30af7906e236a617c9af9548d66db565b83c52a69a21b
