// flow-typed signature: d451203a8ee9327a30e4110c034053e2
// flow-typed version: <<STUB>>/eslint-config-wesm87_v^13.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-wesm87'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-wesm87' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-wesm87/base' {
  declare module.exports: any;
}

declare module 'eslint-config-wesm87/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-wesm87/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-wesm87/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-wesm87/test/test-base' {
  declare module.exports: any;
}

declare module 'eslint-config-wesm87/test/test-react-order' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-wesm87/base.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/base'>;
}
declare module 'eslint-config-wesm87/index' {
  declare module.exports: $Exports<'eslint-config-wesm87'>;
}
declare module 'eslint-config-wesm87/index.js' {
  declare module.exports: $Exports<'eslint-config-wesm87'>;
}
declare module 'eslint-config-wesm87/legacy.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/legacy'>;
}
declare module 'eslint-config-wesm87/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/rules/react-a11y'>;
}
declare module 'eslint-config-wesm87/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/rules/react'>;
}
declare module 'eslint-config-wesm87/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/test/test-base'>;
}
declare module 'eslint-config-wesm87/test/test-react-order.js' {
  declare module.exports: $Exports<'eslint-config-wesm87/test/test-react-order'>;
}
