// flow-typed signature: 70ba95cd7b05f66c380a51c5dff83818
// flow-typed version: <<STUB>>/git-repository_v^0.1.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-repository'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-repository' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-repository/lib/Repository' {
  declare module.exports: any;
}

declare module 'git-repository/lib/utils/cp' {
  declare module.exports: any;
}

declare module 'git-repository/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'git-repository/src/Repository' {
  declare module.exports: any;
}

declare module 'git-repository/src/utils/cp' {
  declare module.exports: any;
}

declare module 'git-repository/src/utils/fs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-repository/lib/Repository.js' {
  declare module.exports: $Exports<'git-repository/lib/Repository'>;
}
declare module 'git-repository/lib/utils/cp.js' {
  declare module.exports: $Exports<'git-repository/lib/utils/cp'>;
}
declare module 'git-repository/lib/utils/fs.js' {
  declare module.exports: $Exports<'git-repository/lib/utils/fs'>;
}
declare module 'git-repository/src/Repository.js' {
  declare module.exports: $Exports<'git-repository/src/Repository'>;
}
declare module 'git-repository/src/utils/cp.js' {
  declare module.exports: $Exports<'git-repository/src/utils/cp'>;
}
declare module 'git-repository/src/utils/fs.js' {
  declare module.exports: $Exports<'git-repository/src/utils/fs'>;
}
