// flow-typed signature: 7ae4c49bc25c9a28dbc83295f9f83b0e
// flow-typed version: <<STUB>>/gulp-nsp_v^2.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-nsp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-nsp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-nsp/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-nsp/gulpfile.js' {
  declare module.exports: $Exports<'gulp-nsp/gulpfile'>;
}
declare module 'gulp-nsp/index' {
  declare module.exports: $Exports<'gulp-nsp'>;
}
declare module 'gulp-nsp/index.js' {
  declare module.exports: $Exports<'gulp-nsp'>;
}
