// flow-typed signature: b064b60bccc5a6df3ff1a1d5c7fe1735
// flow-typed version: <<STUB>>/gulp-istanbul_v^1.1.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-istanbul/index' {
  declare module.exports: $Exports<'gulp-istanbul'>;
}
declare module 'gulp-istanbul/index.js' {
  declare module.exports: $Exports<'gulp-istanbul'>;
}
