// flow-typed signature: eb0612b5f10c4aeeb8f7e217ace17257
// flow-typed version: <<STUB>>/gulp-composer_v^0.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-composer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-composer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-composer/index' {
  declare module.exports: $Exports<'gulp-composer'>;
}
declare module 'gulp-composer/index.js' {
  declare module.exports: $Exports<'gulp-composer'>;
}
