// flow-typed signature: 05c6439878c6e50d86a37e6a549144cf
// flow-typed version: <<STUB>>/mocktail_v^0.3.8/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocktail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocktail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocktail/component/mocktail' {
  declare module.exports: any;
}

declare module 'mocktail/dist/mocktail' {
  declare module.exports: any;
}

declare module 'mocktail/example/Request' {
  declare module.exports: any;
}

declare module 'mocktail/example/Setup' {
  declare module.exports: any;
}

declare module 'mocktail/example/Tests' {
  declare module.exports: any;
}

declare module 'mocktail/gulpfile' {
  declare module.exports: any;
}

declare module 'mocktail/karma.conf' {
  declare module.exports: any;
}

declare module 'mocktail/tests/Export.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/General.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/MockDefault.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/StubDefault.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/StubNamed.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/StubProject.test' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/exports/Default' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/exports/Inject' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/exports/Named' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/Mocks' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/modules/Authentication' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/modules/AuthenticationMock' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/modules/Request' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/modules/RequestMock' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/project/Colours' {
  declare module.exports: any;
}

declare module 'mocktail/tests/test-utils/Setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocktail/component/mocktail.js' {
  declare module.exports: $Exports<'mocktail/component/mocktail'>;
}
declare module 'mocktail/dist/mocktail.js' {
  declare module.exports: $Exports<'mocktail/dist/mocktail'>;
}
declare module 'mocktail/example/Request.js' {
  declare module.exports: $Exports<'mocktail/example/Request'>;
}
declare module 'mocktail/example/Setup.js' {
  declare module.exports: $Exports<'mocktail/example/Setup'>;
}
declare module 'mocktail/example/Tests.js' {
  declare module.exports: $Exports<'mocktail/example/Tests'>;
}
declare module 'mocktail/gulpfile.js' {
  declare module.exports: $Exports<'mocktail/gulpfile'>;
}
declare module 'mocktail/karma.conf.js' {
  declare module.exports: $Exports<'mocktail/karma.conf'>;
}
declare module 'mocktail/tests/Export.test.js' {
  declare module.exports: $Exports<'mocktail/tests/Export.test'>;
}
declare module 'mocktail/tests/General.test.js' {
  declare module.exports: $Exports<'mocktail/tests/General.test'>;
}
declare module 'mocktail/tests/MockDefault.test.js' {
  declare module.exports: $Exports<'mocktail/tests/MockDefault.test'>;
}
declare module 'mocktail/tests/StubDefault.test.js' {
  declare module.exports: $Exports<'mocktail/tests/StubDefault.test'>;
}
declare module 'mocktail/tests/StubNamed.test.js' {
  declare module.exports: $Exports<'mocktail/tests/StubNamed.test'>;
}
declare module 'mocktail/tests/StubProject.test.js' {
  declare module.exports: $Exports<'mocktail/tests/StubProject.test'>;
}
declare module 'mocktail/tests/test-utils/exports/Default.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/exports/Default'>;
}
declare module 'mocktail/tests/test-utils/exports/Inject.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/exports/Inject'>;
}
declare module 'mocktail/tests/test-utils/exports/Named.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/exports/Named'>;
}
declare module 'mocktail/tests/test-utils/Mocks.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/Mocks'>;
}
declare module 'mocktail/tests/test-utils/modules/Authentication.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/modules/Authentication'>;
}
declare module 'mocktail/tests/test-utils/modules/AuthenticationMock.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/modules/AuthenticationMock'>;
}
declare module 'mocktail/tests/test-utils/modules/Request.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/modules/Request'>;
}
declare module 'mocktail/tests/test-utils/modules/RequestMock.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/modules/RequestMock'>;
}
declare module 'mocktail/tests/test-utils/project/Colours.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/project/Colours'>;
}
declare module 'mocktail/tests/test-utils/Setup.js' {
  declare module.exports: $Exports<'mocktail/tests/test-utils/Setup'>;
}
