// flow-typed signature: 8211e94538fda539a06ef98f1c770994
// flow-typed version: <<STUB>>/utils-upsearch_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utils-upsearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'utils-upsearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utils-upsearch/lib/async' {
  declare module.exports: any;
}

declare module 'utils-upsearch/lib/index' {
  declare module.exports: any;
}

declare module 'utils-upsearch/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utils-upsearch/lib/async.js' {
  declare module.exports: $Exports<'utils-upsearch/lib/async'>;
}
declare module 'utils-upsearch/lib/index.js' {
  declare module.exports: $Exports<'utils-upsearch/lib/index'>;
}
declare module 'utils-upsearch/lib/sync.js' {
  declare module.exports: $Exports<'utils-upsearch/lib/sync'>;
}
